<#
    install_airtrack_windows.ps1
    AirTrack Windows - offline installer
    Generates a unique SECRET_KEY and DB credentials on first install.
#>

param (
    [string]$zipPath
)

$logFile = Join-Path $PSScriptRoot 'airtrack_install_log.txt'
"=== AirTrack Windows Installer Log ===`n$(Get-Date)" |
    Out-File $logFile -Encoding UTF8

function Log {
    param([string]$message)
    "$(Get-Date -f 'yyyy-MM-dd HH:mm:ss') | $message" |
        Tee-Object -FilePath $logFile -Append
}

function New-RandomString {
    param([int]$length = 32)
    $bytes = New-Object byte[] $length
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return ([System.BitConverter]::ToString($bytes) -replace '-','').ToLower()
}

# ---------------------------------------------------------------------------
# Preflight checks
# ---------------------------------------------------------------------------

if (-not $zipPath -or -not (Test-Path $zipPath)) {
    Log "ERROR: Zip archive not found: $zipPath"
    Write-Host "ERROR: Zip archive not found:`n$zipPath" -ForegroundColor Red
    exit 1
}
Log "ZIP supplied by installer: $zipPath"

$currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host 'ERROR: please run this installer as Administrator.' -ForegroundColor Red
    Log        'ERROR: script not run as Administrator.'
    exit 1
}
Log 'Administrator rights confirmed.'

if (-not (Get-Command docker -EA SilentlyContinue)) {
    Write-Host 'Docker Desktop not found. Opening download page...' -ForegroundColor Yellow
    Log        'ERROR: Docker CLI not found. Prompting user.'
    Start-Process 'https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe'
    exit 1
}
Log 'Docker CLI found.'

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
$installRoot = Join-Path $env:USERPROFILE 'docker'
$installDir  = Join-Path $installRoot 'AirTrack-Windows'
$tarPath     = Join-Path $installDir  'AirTrack_images.tar'
$envFile     = Join-Path $installDir  '.env'

Log "Will install to: $installDir"
Write-Host "Installing to: $installDir" -ForegroundColor Cyan

New-Item -ItemType Directory -Force -Path $installDir | Out-Null

# ---------------------------------------------------------------------------
# Extract archive
# ---------------------------------------------------------------------------
Write-Host "Extracting archive..." -ForegroundColor Cyan
try {
    Expand-Archive -Path $zipPath -DestinationPath $installDir -Force
    Log 'Archive extracted successfully.'
    Write-Host "Archive extracted." -ForegroundColor Green
}
catch {
    Log "ERROR: Expand-Archive failed: $_"
    Write-Host 'ERROR: failed to extract the application archive.' -ForegroundColor Red
    exit 1
}

# ---------------------------------------------------------------------------
# Generate .env (only on first install - never overwrite existing)
# ---------------------------------------------------------------------------
if (-not (Test-Path $envFile)) {
    Log 'Generating .env with unique credentials...'

    $secretKey    = New-RandomString 32
    $dbPassword   = New-RandomString 16
    $dbRootPass   = New-RandomString 16

    $envContent = @"
# AirTrack Windows - generated by installer on $(Get-Date -f 'yyyy-MM-dd HH:mm:ss')
# Do NOT share or commit this file.

AIRTRACK_ROLE=client
AIRTRACK_UPDATE_MODE=remote
AIRTRACK_FORCE_PUSH=0
AIRTRACK_SYNC_USER=

SECRET_KEY=$secretKey

DB_HOST=airtrack-windows-db
DB_USER=airtrack
DB_PASSWORD=$dbPassword
DB_ROOT_PASSWORD=$dbRootPass
DB_NAME=airtrack

AIRTRACK_APP_DIR=/app
AIRTRACK_STATIC_DIR=/app/static
AIRTRACK_UPDATES_DIR=/app/static/updates
AIRTRACK_LOG_FILE=/app/logs/file_sync.log
AIRTRACK_BACKUP_DIR=/app/backups
AIRTRACK_MAX_ARCHIVES=7
"@

    $envContent | Out-File -FilePath $envFile -Encoding UTF8 -NoNewline
    Log '.env generated successfully.'
    Write-Host ".env created with unique credentials." -ForegroundColor Green
}
else {
    Log '.env already exists - skipping credential generation (upgrade install).'
    Write-Host ".env already exists - preserving existing credentials." -ForegroundColor DarkGray
}

# ---------------------------------------------------------------------------
# Load Docker images
# ---------------------------------------------------------------------------
if (Test-Path $tarPath) {
    Log 'Loading Docker images (this may take a minute)...'
    Write-Host "Loading Docker images..." -ForegroundColor Cyan
    docker load -i $tarPath | Tee-Object -FilePath $logFile -Append

    try {
        Remove-Item -Path $tarPath -Force
        Log 'Docker image tarball removed.'
        Write-Host "Removed Docker image tarball." -ForegroundColor DarkGray
    }
    catch {
        Log "WARNING: Failed to delete ${tarPath}: $_"
        Write-Host "WARNING: Failed to delete ${tarPath}" -ForegroundColor Yellow
    }
}
else {
    Log 'No image tarball found - assuming images already loaded.'
    Write-Host "No image tarball found - skipping docker load." -ForegroundColor DarkGray
}

# ---------------------------------------------------------------------------
# Launch stack
# ---------------------------------------------------------------------------
Set-Location $installDir
Log 'Launching Docker Compose stack...'
Write-Host "Starting AirTrack..." -ForegroundColor Cyan
docker compose -f docker-compose.windows.yml up -d | Tee-Object -FilePath $logFile -Append

Log 'Installation complete.'
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  AirTrack is ready!" -ForegroundColor Green
Write-Host "  Open http://localhost:5000 to begin." -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green